name: 'datasalaries'
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.11
    - pandas=2.2
    - ipykernel=6.29
    - altair-all=5.3
    - jupyterlab=4.1  # JupyterLab
    - matplotlib=3.8 
    - dash=2.18
    - dash-bootstrap-components
    - dash-core-components
    - dash-html-components
    - plotly=6.0
    - vega_datasets
    - geopandas=1.0.1
    - tabulate=0.9  # df.to_markdown()
    - lxml=5.3  # pd.read_html()
    - pip=24.0
    - pip:
        - dash-vega-components
        - pyjanitor==0.30.0
        - gunicorn==23.0.0
        - Flask-Caching==2.3.1
        - pytest==8.1.1